---
title: "线性相关关系"
output:
  html_document: default
  pdf_document: default
---
## 准备数据
```{r}
x1 = c(4,8,12,15,19,35,38,24,28)
x2 = c(3,7,5,9,16,13,19,17,11)
x3 = c(3,1,5,9,3,0,4,1,8)
x = cbind(x1,x2,x3)
y = c(42,36,46,48,40,56,60,64,67)
```

```{r}
plot(x1,y)
```

```{r}
pairs(x,y)
```


## 离均差积和函数求相关系数
+ sum[(x-xbar)(y-ybar)] = sum(x*y) - sum(x)*sum(y)/n
```{r}
lxy = function(x1,y){sum(x1*y) - sum(x1)*sum(y)/length(x1)}
```

```{r}
lxy(x1,x1)
lxy(y,y)
lxy(x1,y)
r = lxy(x1,y)/sqrt(lxy(x1,x1)*lxy(y,y))
r
```
## 直接计算相关系数
```{r}
cor(x,y,method = 'pearson')
```

## 相关系数的显著性检验
Ho:不存在相关关系

```{r}
cor.test(x1,y)
```

矩阵相关系数的假设检验【包已过期】
```{r}
#library(mvstats)
#cor.test(x,y)
```


## 回归
```{r}
formula = lm(y~x1)
plot(x1,y)
# lines(x,36.306 + 3.137*x) # 加任何线
abline(formula) # 加回归线
```

## 回归的假设检验
```{r}
# F检验（方差分析）
anova(formula)
```

```{r}
# t检验
summary(formula)
```

变量选择
```{r}
library(leaps)
library(assertthat)
xy = data.frame(cbind(x,y))
varsel = regsubsets(y~x1+x2+x3,data = xy)
result = summary(varsel)
data.frame(result$outmat,RSS = result$rss,R2= result$rsq,adjR2= result$adjr2,CP= result$cp,BIC= result$bic)
```

```{r}
fm = lm(y~ x1+x2+x3,data = xy)

fm.step = step(fm,direction = "forward")
fm.step = step(fm,direction = 'backward')
fm.step = step(fm,direction = 'both')
```


